### ISSUE TITLE
About Detection

### ISSUE THREAD

**Issue by dzgx** [cuiziteng/ECCV_AERIS#14]
Hello, I have read your paper, I have known your training with LR images but I want to confirm whether your part of detection with LR images(COCO-d) or HR images(reconstruct the original HR images from LR).
Looking forward to your response.

**Comment by cuiziteng** [comment]
Hello, you can see the experiments part in our paper, we complete the detection direct on the original low-resolution images in COCO-d dataset, it could speed up inference time. 

Also our framework propose super-resolution as a self-supervised task on the decoder, rather than super-resolve the degradation images and then test.
